[workspace]
members = [
    "dcmpipe_cli",
    "dcmpipe_dict_builder",
    "dcmpipe_lib",
]
resolver = "2"

# Compile dependencies as optimized, without debug info, to save significant space.
[profile.dev.package."*"]
opt-level = 3
debug = false
strip = true
debug-assertions = false

