[package]
name = "dcmpipe_lib"
version = "0.1.0"
authors = ["neandrake <die.drachen@gmail.com>"]
edition = "2021"

[features]
compress = ["dep:libflate"]

[dependencies]
encoding_rs = "0.8"
libflate = { version = "2.0", optional = true }
thiserror = "1.0"

[lib]
name="dcmpipe_lib"
path="src/lib.rs"
