[package]
name = "dcmpipe_dict_builder"
version = "0.1.0"
authors = ["Christopher Speck <die.drachen@gmail.com>"]
edition = "2021"

[dependencies]
phf_codegen = "0.11"
quick-xml = "0.36"

[lib]
name="dcmpipe_dict_builder"
path="src/lib.rs"
